[package]
name = "beep"
version = "0.3.0"
authors = ["Jack Wrenn <me@jswrenn.com>"]
description = "Beep the PC speaker"
readme = "README.md"
license = "MIT"
repository = "https://github.com/jswrenn/beep"
edition = "2018"

[dependencies]
nix = "0.20"
lazy_static = "1.0"
